title: La1m1e - ВИКИ
description: Страница со всеми пояснениями для стримеров/других заинтересованных
theme: just-the-docs
url: https://just-the-docs.github.io
color_scheme: dark
aux_links:
just_the_docs:
  toc:
    enabled: true